version: "3.8"

services:
  ml_app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
